dist: trusty
sudo: false
language: cpp
compiler: gcc

os: linux

services:
  - docker

before_install:
  - docker pull danoan/min-env:1.boost-filesystem
  - docker build . -t maglac:build

script:
  - docker run maglac:build /magLac/.travis/test-magLac.sh /magLac/build-release
  - docker run maglac:build /magLac/.travis/generate-coverage.sh
  - docker run `bash <(curl -s https://codecov.io/env)` bash <(curl -s https://codecov.io/bash)