dist: trusty
sudo: false
language: cpp
compiler: gcc

os: linux

services:
  - docker

before_install:
  - docker pull danoan/min-env:2.lcov
  - docker build . -t maglac:build

script:
  - docker run maglac:build /magLac/.travis/test-magLac.sh /magLac/build-release
  - docker run maglac:build /magLac/.travis/generate-coverage.sh

after_success:
  - ci_env=$(bash <(curl -s https://codecov.io/env) )
  - ci_post_cov="bash <(curl -s https://codecov.io/bash) -t 82919896-a0e1-4a38-b01c-670f43b7f91d"
  - docker run $ci_env maglac:build bash -c "$ci_post_cov"
