#!/bin/bash

PROJECT_DIR=$(realpath $1)
BUILD_DIR=$(realpath $2)
INSTALL_PATH=$(realpath $3)
BUILD_TYPE=$4
COVERAGE=$5

CPP="/usr/include;/usr/local/include"

mkdir -p $BUILD_DIR
cd $BUILD_DIR

cmake $PROJECT_DIR \
-DCMAKE_BUILD_TYPE=$BUILD_TYPE \
-DCMAKE_PREFIX_PATH=$CPP \
-DCMAKE_INSTALL_PREFIX=$INSTALL_PATH \
-DBUILD_TESTS=ON \
-DBUILD_EXAMPLES=ON \
-DCOVERAGE=$COVERAGE \
-DCMAKE_BUILD_TYPE=$BUILD_TYPE

make
make install

