#!/bin/bash

PROJECT_DIR=$(realpath $1)
BUILD_DIR=$(realpath $2)
INSTALL_PATH=$(realpath $3)
BUILD_TYPE=$4

CPP="/usr/include;/usr/local/include"

mkdir -p $BUILD_DIR
cd $BUILD_DIR

cmake $PROJECT_DIR \
-DCMAKE_BUILD_TYPE=$BUILD_TYPE \
-DCMAKE_PREFIX_PATH=$CPP \
-DCMAKE_INSTALL_PREFIX=$INSTALL_PATH \
-DBUILD_TESTS=ON \
-DBUILD_EXAMPLES=ON \
-DCMAKE_BUILD_TYPE=$BUILD_TYPE \
-DBOOST_INCLUDE_DIRS=$BOOST_INCLUDE_DIRS \
-DBOOST_LIBS_DIR=$BOOST_LIBS_DIR

make
make install

